webapp/Controllers/Business/ContosoUniController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SmartAdminMvc.Controllers.Business
{
    [Authorize]
    public class ContosoUniController : Controller
    {
        // GET: ContosoUni
        public ActionResult ContosoUni()
        {
            return View();
        }
    }
}

webapp/Controllers/Business/JSController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SmartAdminMvc.Controllers.Business
{
    [Authorize]
    public class JSController : Controller
    {
        
        public ActionResult JScript()
        {
            return View();
        }
        public ActionResult JScriptBackGround()
        {
            return View();
        }
    }
}

webapp/Controllers/Business/TableauDashController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SmartAdminMvc.Controllers.Business
{
    [Authorize]
    public class TableauDashController : Controller
    {
        
        public ActionResult TableauIndex()
        {
            return View();
        }

        public ActionResult TableauQuadrant()
        {
            return View();
        }

        public ActionResult TableauBank()
        {
            return View();
        }

        public ActionResult TableauCoal()
        {
            return View();
        }
    }
}

webapp/Views/Shared/_Aside.cshtml
    <!-- Left panel : Navigation area -->
<!-- Note: This width of the aside area can be adjusted through LESS variables -->
<aside id="left-panel">

    <!-- User info -->
    @{ Html.RenderPartial("_CurrentUser"); }
    <!-- end user info -->
     
    <!--NAVIGATION-->
    <nav>
        <ul>
            <li class="@Html.RouteIf("index", "active")">
                <a href="@Url.Action("index", "home")" title="Welcome to the archipelago"><i class="fa fa-lg fa-fw fa-home"></i>
                <span class="menu-item-parent">Dashboard</span></a>
            </li>
            
            <li class="@Html.RouteIf("transportIndex", "active")">
                <a href="@Url.Action("transportIndex", "transportOpt")" title="Upload an Excel template into a database. The optimum supply is then calculated via Windows Solver Foundation">
                    <i class="fa fa-lg fa-fw fa-truck "></i>
                    <span class="menu-item-parent">Transport Optimisation</span>
                </a>
            </li>

            <li class="@Html.RouteIf("TransGraphIndex", "active")">
                <a href="#" )" title="Display the results of the transport optimisation problem in chart form"><i class="fa fa-lg fa-fw fa-bar-chart-o"></i> <span class="menu-item-parent">Graphical Display</span></a>
                <ul>
                    <li class="@Html.RouteIf("TransGraphJS", "active")">
                        <a href="@Url.Action("TransGraphJS", "TransportGraph")" title="Transport Optimisation Problem visualised with ChartJS">ChartJS</a>
                        <!--<span class="menu-item-parent">-->
                    </li>
                    <li class="@Html.RouteIf("TransGraphFusion", "active")">
                        <a href="@Url.Action("TransGraphFusion", "TransportGraph")" title="Transport Optimisation Problem visualised with Fusion Charts">Fusion Charts</a>
                    </li>
                    @*<li class="@Html.RouteIf("FusionTest", "active")">
                        <a href="@Url.Action("FusionTest", "TransportGraph")" title="Fusion Charts">Fusion test</a>
                    </li>*@
                </ul>
            </li>

            <li class="@Html.RouteIf("contosouni", "active")">
                <a href="@Url.Action("contosouni", "ContosoUni")" title="A demonstration of advanced database techniques using entity framework">
                    <i class="fa fa-lg fa-fw fa-graduation-cap"></i>
                    <span class="menu-item-parent">Contoso University</span>
                </a>
            </li>
    
            <li class="@Html.RouteIf("TableauIndex", "active")">
                <a href="#")" title="Tableau dashboards allow fluent display of key relations between data"><i class="fa fa-lg fa-fw fa-signal"></i> <span class="menu-item-parent">Tableau Dashboards</span></a>
                <ul>
                    <li class="@Html.RouteIf("TableauQuadrant", "active")">
                        <a href="@Url.Action("TableauQuadrant", "TableauDash")" title="Startup Quadrant">Startup Quadrant</a>
                    <!--<span class="menu-item-parent">-->
                    </li>
                    <li class="@Html.RouteIf("TableauBank", "active")">
                        <a href="@Url.Action("TableauBank", "TableauDash")" title="UK Bank">UK Bank</a>
                    </li>
                    <li class="@Html.RouteIf("TableauCoal", "active")">
                        <a href="@Url.Action("TableauCoal", "TableauDash")" title="Coal Terminal Analysis">Coal Terminal</a>
                    </li>
                </ul>
            </li>
            @*<li class="@Html.RouteIf("TableauIndex", "active")">
                <a href="@Url.Action("TableauIndex", "TableauDash")" title="Tableau dashboards allow fluent display of key relations between data">
                    <i class="fa fa-lg fa-fw fa-signal"></i>
                    <span class="menu-item-parent">Tableau Dashboards</span>
                </a>
            </li>*@

            @*<li class="@Html.RouteIf("JScript", "active")">
                <a href="#" )" title="Tableau dashboards allow fluent display of key relations between data"><i class="fa fa-lg fa-fw fa-dollar fa-spin"></i> <span class="menu-item-parent">Javascript</span></a>
                <ul>
                    <li class="@Html.RouteIf("JScriptBackGround", "active")">
                        <a href="@Url.Action("JScriptBackGround", "JS")" title="JavaScript running in the background">Javascript</a>
                    </li>
                </ul>       
            </li>*@
        
    </nav>
    <span class="minifyme" data-action="minifyMenu">
        <i class="fa fa-arrow-circle-left hit"></i>
    </span>

</aside>
<!-- END NAVIGATION -->

webapp/Views/Shared/_CurrentUser.cshtml
<div class="login-info">
    <span>
        <a href="javascript:void(0);" id="show-shortcut" data-action="toggleShortcut">
            <img src="~/Content/img/avatars/male.png" alt="me" class="online" />
            <span class="semi-bold">@User.Identity.Name.ToLower()</span>
        </a>
    </span>
</div>

webapp/Views/Shared/_Footer.cshtml
    <!-- PAGE FOOTER -->
<div class="page-footer">
    <div class="row">
        <div class="col-xs-12 col-sm-6">
            <span class="txt-color-white">Archipelago<span class="hidden-xs"> - Cloud Platform</span> © 2016</span>
        </div>

        <div class="col-xs-6 col-sm-6 text-right hidden-xs">
            <div class="txt-color-white inline-block">
                <i class="txt-color-blueLight hidden-mobile">Last account activity <i class="fa fa-clock-o"></i> <strong>52 mins ago &nbsp;</strong> </i>
                <div class="btn-group dropup">
                    <button class="btn btn-xs dropdown-toggle bg-color-blue txt-color-white" data-toggle="dropdown">
                        <i class="fa fa-link"></i> <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu pull-right text-left">
                        <li>
                            <div class="padding-5">
                                <p class="txt-color-darken font-sm no-margin">Download Progress</p>
                                <div class="progress progress-micro no-margin">
                                    <div class="progress-bar progress-bar-success" style="width: 50%;"></div>
                                </div>
                            </div>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <div class="padding-5">
                                <p class="txt-color-darken font-sm no-margin">Server Load</p>
                                <div class="progress progress-micro no-margin">
                                    <div class="progress-bar progress-bar-success" style="width: 20%;"></div>
                                </div>
                            </div>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <div class="padding-5">
                                <p class="txt-color-darken font-sm no-margin">Memory Load <span class="text-danger">*critical*</span></p>
                                <div class="progress progress-micro no-margin">
                                    <div class="progress-bar progress-bar-danger" style="width: 70%;"></div>
                                </div>
                            </div>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <div class="padding-5">
                                <button class="btn btn-block btn-default">refresh</button>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END PAGE FOOTER -->

webapp/Views/Shared/_Header.cshtml
    <!-- HEADER -->
<header id="header">
    <div id="logo-group" style="opacity:0">

    </div>
    
    <section id="top-right">
        @if (@Model is HelperResult)
        {
            @Model
        }
        else
        {
            <div class="pull-right">
                @Html.Partial("_TopRight")
            </div>
        }
    </section>
</header>
<!-- END HEADER -->

webapp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en-us" id="@ViewBag.PageId" class="@Settings.CurrentTheme">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title> Archipelago </title>
    <meta name="description" content="">
    <meta name="author" content="">

    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

    <!-- Basic Styles -->
    @Styles.Render("~/content/smartadmin")
    <!-- FAVICONS -->
    <link rel="shortcut icon" href="~/content/img/favicon/favicon.ico" type="image/x-icon">
    <link rel="icon" href="~/content/img/favicon/favicon.ico" type="image/x-icon">

    <!-- GOOGLE FONT -->
    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,300,400,700">

    <!-- Specifying a Webpage Icon for Web Clip
         Ref: https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html -->
    <link rel="apple-touch-icon" href="~/content/img/splash/sptouch-icon-iphone.png">
    <link rel="apple-touch-icon" sizes="76x76" href="~/content/img/splash/touch-icon-ipad.png">
    <link rel="apple-touch-icon" sizes="120x120" href="~/content/img/splash/touch-icon-iphone-retina.png">
    <link rel="apple-touch-icon" sizes="152x152" href="~/content/img/splash/touch-icon-ipad-retina.png">

    <!-- iOS web-app metas : hides Safari UI Components and Changes Status Bar Appearance -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">

    <!-- Startup image for web apps -->
    <link rel="apple-touch-startup-image" href="~/content/img/splash/ipad-landscape.png" media="screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:landscape)">
    <link rel="apple-touch-startup-image" href="~/content/img/splash/ipad-portrait.png" media="screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:portrait)">
    <link rel="apple-touch-startup-image" href="~/content/img/splash/iphone.png" media="screen and (max-device-width: 320px)">

    
</head>
<body class="@ViewBag.PageClass smart-style-1" @*@Settings.CurrentTheme*@>
    @{ Html.RenderPartial("_Header", RenderSection("topright", false)); }
    @{ Html.RenderPartialIf("_Aside", Request.IsAuthenticated); }
    <div id="main" role="main">
        @{ Html.RenderPartialIf("_Ribbon", Request.IsAuthenticated); }
        @RenderBody()
    </div>
    @if (Request.IsAuthenticated)
    {
        Html.RenderPartial("_Footer");
        Html.RenderPartialIf("_Tiles", Settings.EnableTiles);
    }
    @{ Html.RenderPartial("_Scripts", RenderSection("pagespecific", false)); }
</body>

</html>

webapp/Views/Shared/_Ribbon.cshtml
<!-- RIBBON -->
<div id="ribbon">

    <span class="ribbon-button-alignment">
        <span id="refresh" class="btn btn-ribbon" data-action="resetWidgets" data-title="refresh" rel="tooltip" data-placement="bottom" data-original-title="<i class='text-warning fa fa-warning'></i> Warning! This will reset all your widget settings." data-html="true">
						<i class="fa fa-refresh"></i>
					</span>
    </span>

    <!-- breadcrumb -->
    <ol class="breadcrumb">
        <li>Home</li>
        <li>Dashboard</li>
    </ol>
    <!-- end breadcrumb -->
    <!-- You can also add more buttons to the
    ribbon for further usability

    Example below:

    <span class="ribbon-button-alignment pull-right">
    <span id="search" class="btn btn-ribbon hidden-xs" data-title="search"><i class="fa-grid"></i> Change Grid</span>
    <span id="add" class="btn btn-ribbon hidden-xs" data-title="add"><i class="fa-plus"></i> Add</span>
    <span id="search" class="btn btn-ribbon" data-title="search"><i class="fa-search"></i> <span class="hidden-mobile">Search</span></span>
    </span> -->

</div>
<!-- END RIBBON -->

webapp/Views/Shared/_Scripts.cshtml
<!-- Link to Google CDN's jQuery + jQueryUI; fall back to local -->

@*<script src="//ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
<script> if (!window.jQuery) { document.write('<script src="/scripts/libs/jquery-2.1.1.min.js"><\/script>'); } </script>*@


<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
<script> if (!window.jQuery.ui) { document.write('<script src="/scripts/libs/jquery-ui-1.10.3.min.js"><\/script>'); } </script>


<!-- Core Scripts -->
@Scripts.Render("~/scripts/smartadmin")

@if (Request.IsAuthenticated)
{
    <!-- PACE LOADER - Use ajax loading (caution: uses lots of memory on iDevices)-->
    <script data-pace-options='{ "restartOnRequestAfter": true }' src="~/scripts/plugin/pace/pace.min.js"></script>
    
    //<script src="/scripts/demo.min.js"></script>
}

<!-- Voice command : plugin -->
<script src="~/scripts/speech/voicecommand.min.js"></script>


@*@Scripts.Render("~/scripts/smart-chat")*@

<!-- DataTables -->
@Scripts.Render("~/scripts/datatables")

<!-- jQGrid -->
@Scripts.Render("~/scripts/jq-grid")

<!-- Forms -->
@Scripts.Render("~/scripts/forms")

<!-- Flot Chart  -->
@Scripts.Render("~/scripts/charts")

<!-- Vector Maps  -->
@Scripts.Render("~/scripts/vector-map")

<!-- Full Calendar -->
@Scripts.Render("~/scripts/full-calendar")

<!-- GLOBAL FUNCTIONS -->
<script>
    $(document).ready(function () {
        pageSetUp();
        drawBreadCrumb();
    });
</script>

@if (@Model is HelperResult)
{
    @Model
}
<!-- GOOGLE ANALYTICS CODE Below-->
    @*<script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'xx-xxxxxxxx-x']);
    _gaq.push(['_trackPageview']);

    (function () {
        var ga = document.createElement('script');
        ga.type = 'text/javascript';
        ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(ga, s);
    })();
</script>*@

webapp/Views/Shared/_Tiles.cshtml
<!-- SHORTCUT AREA : With large tiles (activated via clicking user name tag)
Note: These tiles are completely responsive,
you can add as many as you like
-->
@*<div id="shortcut">
    <ul>
        <li>
            <a href="@Url.Action("inbox", "home")" class="jarvismetro-tile big-cubes bg-color-blue"> <span class="iconbox"> <i class="fa fa-envelope fa-4x"></i> <span>Mail <span class="label pull-right bg-color-darken">14</span></span> </span> </a>
        </li>
        <li>
            <a href="@Url.Action("calendar", "home")" class="jarvismetro-tile big-cubes bg-color-orangeDark"> <span class="iconbox"> <i class="fa fa-calendar fa-4x"></i> <span>Calendar</span> </span> </a>
        </li>
        <li>
            <a href="@Url.Action("googlemap", "home")" class="jarvismetro-tile big-cubes bg-color-purple"> <span class="iconbox"> <i class="fa fa-map-marker fa-4x"></i> <span>Maps</span> </span> </a>
        </li>
        <li>
            <a href="@Url.Action("invoice", "misc")" class="jarvismetro-tile big-cubes bg-color-blueDark"> <span class="iconbox"> <i class="fa fa-book fa-4x"></i> <span>Invoice <span class="label pull-right bg-color-darken">99</span></span> </span> </a>
        </li>
        <li>
            <a href="@Url.Action("gallery", "appviews")" class="jarvismetro-tile big-cubes bg-color-greenLight"> <span class="iconbox"> <i class="fa fa-picture-o fa-4x"></i> <span>Gallery </span> </span> </a>
        </li>
        <li>
            <a href="@Url.Action("profile", "appviews")" class="jarvismetro-tile big-cubes selected bg-color-pinkDark"> <span class="iconbox"> <i class="fa fa-user fa-4x"></i> <span>My Profile </span> </span> </a>
        </li>
    </ul>
</div>*@
<!-- END SHORTCUT AREA -->

webapp/Views/Shared/_TopRight.cshtml
<!-- collapse menu button -->
<div id="hide-menu" class="btn-header pull-right">
    <span> <a href="javascript:void(0);" data-action="toggleMenu" title="Collapse Menu"><i class="fa fa-reorder"></i></a> </span>
</div>
<!-- end collapse menu -->
<!-- #MOBILE -->
<!-- Top menu profile link : this shows only when top menu is active -->
<ul id="mobile-profile-img" class="header-dropdown-list hidden-xs padding-5">
    <li class="">
        <a href="#" class="dropdown-toggle no-margin userdropdown" data-toggle="dropdown">
            <img src="~/content/img/avatars/sunny.png" alt="John Doe" class="online" />
        </a>
        <ul class="dropdown-menu pull-right">
            <li>
                <a href="javascript:void(0);" class="padding-10 padding-top-0 padding-bottom-0"><i class="fa fa-cog"></i> Setting</a>
            </li>
            <li class="divider"></li>
            <li>
                <a href="#" class="padding-10 padding-top-0 padding-bottom-0"> <i class="fa fa-user"></i> Profile</a>
            </li>
            <li class="divider"></li>
            <li>
                <a href="javascript:void(0);" class="padding-10 padding-top-0 padding-bottom-0" data-action="toggleShortcut"><i class="fa fa-arrow-down"></i> <>S</>hortcut</a>
            </li>
            <li class="divider"></li>
            <li>
                <a href="javascript:void(0);" class="padding-10 padding-top-0 padding-bottom-0" data-action="launchFullscreen"><i class="fa fa-arrows-alt"></i> Full <>S</>creen</a>
            </li>
            <li class="divider"></li>
            <li>
                <a href="@Url.Action("login", "account")" class="padding-10 padding-top-5 padding-bottom-5" data-action="userLogout"><i class="fa fa-sign-out fa-lg"></i> <strong><>L</>ogout</strong></a>
            </li>
        </ul>
    </li>
</ul>

<!-- logout button -->
<div id="logout" class="btn-header transparent pull-right">
    <span> <a href="@Url.Action("login", "account")" title="Sign Out" data-action="userLogout" data-logout-msg="You can improve your security further after logging out by closing this opened browser"><i class="fa fa-sign-out"></i></a> </span>
</div>

<!-- search mobile button (this is hidden till mobile view port) -->
<div id="search-mobile" class="btn-header transparent pull-right">
    <span> <a href="javascript:void(0)" title="Search"><i class="fa fa-search"></i></a> </span>
</div>

<!-- fullscreen button -->
<div id="fullscreen" class="btn-header transparent pull-right">
    <span> <a href="javascript:void(0);" data-action="launchFullscreen" title="Full Screen"><i class="fa fa-arrows-alt"></i></a> </span>
</div>